export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_START = "FETCH_START";
export const LOAD_DATA = "LOAD_DATA";
export const SET_DATA_MODIFIED_FLAG = "SET_DATA_MODIFIED_FLAG";
